[build.environment]
  NODE_VERSION = "16"

[build]
  base = "docs/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "docs/.vuepress/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
