[build.environment]
  NODE_VERSION = "16"

[build]
  base = "docs/"
  command = "npm run build"
  publish = ".vuepress/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
