
[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"
  
[build]
  base = "examples/demo-nuxt/"
  publish = "dist"
  command = "npx pnpm -w run vite-plugin:build && npx pnpm -w run demo-nuxt:build"
