version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.1
  slack: circleci/slack@4.10.1

jobs:
  prepare:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    steps:
      - checkout
      - run: pnpm config set auto-install-peers true
      - run: pnpm install --shamefully-hoist=true
      - run: pnpm run build
      - run: pnpm run test
      - sonarcloud/scan
  plugin:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    steps:
      - run: pnpm run plugin:build
  demo:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    steps:
      - run: pnpm run demo:build
  demo-ssg:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    steps:
      - run: pnpm run demo:build
  docs:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    steps:
      - run: pnpm run docs:build
  deploy:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    steps:
      - slack/notify:
          channel: circleci
          event: always

workflows:
  version: 2
  build_test_all:
    jobs:
      - prepare:
          context: 
            - SonarCloud
      - plugin:
          requires:
            - prepare
      - demo:
          requires:
            - prepare
            - plugin
      - demo-ssg:
          requires:
            - prepare
            - plugin
      - docs:
          requires:
            - prepare
            - plugin
      - deploy:
          requires:
            - prepare
            - plugin
            - demo
            - demo-ssg
            - docs
          context: 
            - Slack