version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.1
  slack: circleci/slack@4.10.1

executors:
  pnpm-executor:
    docker:
      - image: vernaillen/circleci-pnpm:18.4.0
    working_directory: /tmp/workspace

jobs:
  prepare:
    executor: pnpm-executor
    steps:
      - run: mkdir -p workspace

      - checkout
      - run: pnpm config set auto-install-peers true
      - run: pnpm install --shamefully-hoist=true
      - run: pnpm run build
      - run: pnpm run test
      - sonarcloud/scan
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - package.json
            - pnpm-lock.yaml
            - pnpm-workspace.yaml
            - examples
            - docs
  plugin:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run plugin:build
  demo:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run demo:build
  demo-ssg:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run demo:build
  docs:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run docs:build
  deploy:
    executor: pnpm-executor
    steps:
      - slack/notify:
          channel: circleci
          event: always

workflows:
  version: 2
  build_test_all:
    jobs:
      - prepare:
          context: 
            - SonarCloud
      - plugin:
          requires:
            - prepare
      - demo:
          requires:
            - prepare
            - plugin
      - demo-ssg:
          requires:
            - prepare
            - plugin
      - docs:
          requires:
            - prepare
            - plugin
      - deploy:
          requires:
            - prepare
            - plugin
            - demo
            - demo-ssg
            - docs
          context: 
            - Slack