version: 2.1

orbs:
  node: circleci/node@5.1.0
  sonarcloud: sonarsource/sonarcloud@1.1.1
  slack: circleci/slack@4.12.0

executors:
  pnpm-executor:
    docker:
      - image: vernaillen/circleci-pnpm:19.3.0
    working_directory: /tmp/workspace

jobs:
  prepare-and-test:
    executor: pnpm-executor
    steps:
      - checkout
      - run: pnpm config set auto-install-peers true
      - run: pnpm install --shamefully-hoist=true
      - run: pnpm run test
      - sonarcloud/scan
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - package.json
            - pnpm-lock.yaml
            - pnpm-workspace.yaml
            - node_modules
            - sonar-project.properties
            - vite-plugin
            - examples
            - docs
      - slack/notify:
          channel: circleci
          event: fail
  build-vite-plugin:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run vite-plugin:build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - vite-plugin
      - slack/notify:
          channel: circleci
          event: fail
  build-docs:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run docs:build
      - slack/notify:
          channel: circleci
          event: fail
  build-demo:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run demo:build
      - slack/notify:
          channel: circleci
          event: fail
  build-demo-ssg:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run demo-ssg:build
      - slack/notify:
          channel: circleci
          event: fail
  build-demo-nuxt:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pnpm run demo-nuxt:build
      - slack/notify:
          channel: circleci
          event: fail
  deploy:
    executor: pnpm-executor
    steps:
      - slack/notify:
          channel: circleci
          event: always

workflows:
  version: 2
  build_test_all:
    jobs:
      - prepare-and-test:
          context: 
            - SonarCloud
            - Slack
      - build-vite-plugin:
          requires:
            - prepare-and-test
          context: 
            - Slack
      - build-docs:
          requires:
            - prepare-and-test
          context: 
            - Slack
      - build-demo:
          requires:
            - build-vite-plugin
          context: 
            - Slack
      - build-demo-ssg:
          requires:
            - build-vite-plugin
          context: 
            - Slack
      - build-demo-nuxt:
          requires:
            - build-vite-plugin
          context: 
            - Slack
      - deploy:
          requires:
            - build-demo
            - build-demo-ssg
            - build-demo-nuxt
            - build-docs
          context: 
            - Slack