version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.0

jobs:
  build_test_all:
    docker:
      - image: vernaillen/circleci-pnpm:18.2.0
    steps:
      - checkout
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - sonarcloud/scan

workflows:
  version: 2
  build_all:
    jobs:
      - build_test_all:
          context: SonarCloud