version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.3

executors:
  node-executor:
    docker:
      - image: cimg/node:16.14
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  plugin:
    executor: node/default
    steps:
      - node/run:
          npm-run: build
      - run: npm run lint
      - sonarcloud/scan

workflows:
  version: 2
  build_all:
    jobs:
      - plugin:
          context: SonarCloud
