import type { Options } from 'audiomotion-analyzer'

const DefaultOptions: Options = {
  alphaBars: false,
  barSpace: 0.1,
  bgAlpha: 0.7,
  fftSize: 8192,
  fillAlpha: 1,
  gradient: 'classic',
  ledBars: false,
  lineWidth: 0,
  loRes: false,
  lumiBars: false,
  maxDecibels: -25,
  maxFreq: 22000,
  minDecibels: -85,
  minFreq: 20,
  mirror: 0,
  mode: 0,
  outlineBars: false,
  overlay: false,
  radial: false,
  reflexAlpha: 0.15,
  reflexBright: 1,
  reflexFit: true,
  reflexRatio: 0,
  showBgColor: true,
  showFPS: false,
  showPeaks: true,
  showScaleX: true,
  showScaleY: false,
  smoothing: 0.5,
  spinSpeed: 0,
  splitGradient: false,
  start: true,
  channelLayout: 'single',
  useCanvas: true,
  volume: 1,
  height: 270
}
export default DefaultOptions
