[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  base = "examples/demo/"
  publish = "dist"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm -w run vite-plugin:build && npx pnpm -w run demo:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"