[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  base = "docs/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm -w run docs:build"
  publish = ".vitepress/dist"

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
